---
title: "Resume"
---

# Education

**The University of British Columbia (UBC) | Vancouver, BC, Canada** <span style="float:right;">09/2025–05/2026</span>  
Master of Geomatics for Environmental Management

**The University of British Columbia (UBC) | Vancouver, BC, Canada** <span style="float:right;">09/2021–08/2024</span>  
Bachelor of Science in Urban Forestry with Honours, Minor in Urban Greenspace Management  
Dean of Forestry Scholarship (2023–2024)

**Fujian Agriculture and Forestry University (FAFU) | Fujian, China** <span style="float:right;">09/2018–08/2021</span>  
Bachelor of Science in Ecology

# Academic Experience

*Urban Heat Island Effect Visualization Project, UBC, Vancouver, BC* <span style="float:right;">09/2022–04/2023</span>

-  Generated the Heat Vulnerable Areas and Ocean Heat Capacity maps by using ArcGIS and ENVI remote sensing 
-  Analyzed the Urban Heat Island Effect by incorporating the GIS database of land surface temperature, vegetation classification, building, roads, and campus boundary from satellite images
-  Accurately conducted a regression analysis of the geodata, discovering correlation between parameters regarding the p-value and R square value in Office Excel

*Water-Crisis Research Project, UBC, Vancouver, BC* <span style="float:right;">11/2022–01/2023</span>

-  Conducted thorough research on water conservation policies and initiatives in South Africa to discover potential implications from the case study of the Day Zero in Cape Town City
-  Facilitated ongoing discussions with team members and mentor through weekly online meetings, forming meeting records, detailed bibliography and the research question
-  Composed a well-arranged poster with diagrams and references to interpret the water crisis in Cape Town City and proposed a couple of potential solutions, integrating the government, organizations, and citizens’ inner power

*Forest Therapy Project Assistant, UBC, Vancouver, BC* <span style="float:right;">06/2023–09/2023</span>

-  Independently associated the curriculum development for the 'International Forestry' course of ten comprehensive chapters, summarizing concepts and case studies from primary academic references while ensuring meticulous alignment of content
-  Conducted intensive literature reviews, website and relevant multimedia resources searching for each lecture chapter, while appropriately citing all references and producing 100 pages of slides per week

*Urban Forestry Research Assistant, UBC, Vancouver, BC* <span style="float:right;">06/2022–09/2022</span>

-  Collected and classified documents on urban forestry from all Canadian municipalities to create a comprehensive database to help with the decision-making of researchers and governments 
-  Skimmed through government documents including stormwater management, climate change mitigation, wildfire strategy, street tree bylaw, invasive species control strategy, and land use plan. Incorporated all relevant documents and contributed to database build-up

# Work & Volunteer

*Land Surveyor Assistant, Amray Land Surveying Ltd., Burnaby, BC* <span style="float:right;">10/2024–01/2025</span>

-  Efficiently and precisely set up Total Station at various locations, controlling the errors below 2 centimetres or 5 millimetres depending on the projects, and recording detailed field notes
-  Familiar with reading surveying maps and the process of measuring different kinds of projects, including posting, reposting, on-site layout, topography, new engineering contract, and benchmark setting
-  Precisely recorded the corresponding code of measured objects, exporting the data to the database for designers

*Beaty Biodiversity Museum Educator, UBC, Vancouver, BC* <span style="float:right;">10/2023–05/2024</span>

-  Provided engaging interpretations of creature and fossil specimens to museum visitors with inclusive language and customer service attitude, informing instructions of touchable specimens to visitors  
-  Answered and addressed questions about specimens, museum layout, and seasonal activities for visitors, communicating with fellow educators via radio and collaborating to facilitate smooth closing of the museum

*Class Notetaker, UBC, Vancouver, BC* <span style="float:right;">10/2022–01/2024</span>

-  Recorded real-time, detailed notes during professor’s lectures for students with disabilities and uploaded notes to the website twice a week with well-organized information
-  Consistently attended all classes punctually, maintaining open communication with the professor to ensure accuracy and completeness of notes

*Inclusive Forestry Peer Mentor, UBC, Vancouver, BC* <span style="float:right;">05/2023–08/2023</span>

-  Shared valuable insights and experiences of living in Canada and studying at UBC with program newcomers, fostering a sense of learning community and support
-  Actively participated in a peer mentor seminar discussing issues such as academic plagiarism, contributing personal experiences to enrich and facilitate workshops
-  Provided insightful advice to event organizers on crucial topics including traffic regulations, migration document extensions, and other related matters, ensuring smooth event operations

*Eco-Steward, Stanley Park, Vancouver, BC* <span style="float:right;">08/2022–04/2023</span>

-  Identified and removed patches of invasive species (e.g., Himalayan blackberry, English ivy) 
-  Planted native species (e.g., vine maple, huckleberry, deer fern, etc.) in Stanley Park by finding a suitable position to reach a higher survival rate
-  Watered new-planted vegetation in the following weeks and approximately 80% of them survived the drought

# Qualifications

-  *Software*: Proficient in ArcGIS Pro, QGIS, Google Earth Engine, Rstudio, and Microsoft Office, and capable with Python coding, Adobe Creative Cloud Suits, i-Tree tool kit, Rhino-3D modelling, and ENVI remote sensing tools
-  *Research ability*: Demonstrated capability of conducting comprehensive literature reviews independently, efficiently gathering and analyzing information from diverse sources
-  *Academic Writing & Communication*: Demonstrated ability to produce high-quality essays and reports. Strong capability in delivering presentations to diverse audiences in both written reports and verbal communication
-  *Bilingual Speaker*: English (Proficient), Mandarin (Native)